server:
  port: 7004

spring:
  jpa:
    properties:
      hibernate:
        default_schema: dev
  datasource:
    host: localhost
    port: 30001
    username: user
    password: password

oauth2:
  auth-server-host: https://localhost:7003
  auth-login-base-uri: "/oauth2"
  auth-code-redirect-uri: https://localhost:3000/api/oauth/authcode/code
  post-auth-redirect: https://localhost:3000
  client-key: a4cc4fef-564e-44c1-82af-45572f124c1a
  client-secret: 1566aadf-800f-4a9d-9828-6a77426a53b5

logging:
  level:
    io.craigmiller160.authmanagementservice: DEBUG
    io.craigmiller160.webutils: DEBUG
    io.craigmiller160.oauth2: DEBUG
