server:
  port: 7004

spring:
  jpa:
    properties:
      hibernate:
        default_schema: dev
  datasource:
    host: localhost
    port: 30001
    username: user
    password: password

logging:
  level:
    io.craigmiller160.authmanagementservice: DEBUG
    io.craigmiller160.webutils: DEBUG
    io.craigmiller160.oauth2: DEBUG
