server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/auth-manage.p12
    key-store-password: auth-manage-pass
    use-ssl: true

spring:
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/oauth2_server

oauth2:
  auth-login-base-uri: "/oauth2"
  auth-code-redirect-uri: "/api/oauth/authcode/code"
  post-auth-redirect: "/"
  client-name: auth-management-service
  cookie-name: auth-management-token
  cookie-max-age-secs: 86400
  insecure-paths: "/actuator/health"

logging:
  level:
    root: ERROR
