server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/auth-manage.p12
    key-store-password: auth-manage-pass
    use-ssl: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/oauth2_server

oauth2:
  auth-server-host: https://localhost:7003
  auth-code-redirect-uri: https://localhost:3000/api/oauth/authcode/code
  post-auth-redirect: https://localhost:3000
  client-name: auth-management-service
  client-key: a4cc4fef-564e-44c1-82af-45572f124c1a
  client-secret: 1566aadf-800f-4a9d-9828-6a77426a53b5
  cookie-name: auth-management-token
  cookie-max-age-secs: 86400

logging:
  level:
    root: ERROR
