server:
  port: 7004
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/auth-manage.p12
    key-store-password: auth-manage-pass

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dev
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.hbm2ddl.delimiter: ';'
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      javax.persistence.schema-generation.create-source: metadata
      javax.persistence.schema-generation.scripts.action: drop-and-create
      javax.persistence.schema-generation.scripts.create-target: sql/create-schema.sql
      javax.persistence.schema-generation.scripts.drop-target: sql/drop-schema.sql
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:30001/oauth2_server
    username: user
    password: password

oauth2:
  auth-server-host: https://localhost:7003
  auth-code-redirect-uri: https://localhost:3000/api/oauth/authcode/code
  post-auth-redirect: https://localhost:3000
  client-name: auth-management-service
  client-key: a4cc4fef-564e-44c1-82af-45572f124c1a
  client-secret: 1566aadf-800f-4a9d-9828-6a77426a53b5
  cookie-name: auth-management-token
  cookie-max-age-secs: 86400

logging:
  level:
    root: ERROR
    io.craigmiller160.authmanagementservice: DEBUG
    io.craigmiller160.webutils: DEBUG
    io.craigmiller160.oauth2: DEBUG
    # TODO remove this log line
    com.graphql-java: DEBUG
