server:
  port: 7004
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/auth-server.p12
    key-store-password: auth-server-pass

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dev
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.hbm2ddl.delimiter: ';'
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      javax.persistence.schema-generation.create-source: metadata
      javax.persistence.schema-generation.scripts.action: drop-and-create
      javax.persistence.schema-generation.scripts.create-target: sql/create-schema.sql
      javax.persistence.schema-generation.scripts.drop-target: sql/drop-schema.sql
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:30001/oauth2_server
    username: user
    password: password