server:
  port: 8443

spring:
  jpa:
    properties:
      hibernate:
        default_schema: prod

logging:
  level:
    io.craigmiller160.authmanagementservice: INFO
    io.craigmiller160.webutils: INFO
    io.craigmiller160.oauth2: INFO
