apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-management-service
  template:
    metadata:
      labels:
        app: auth-management-service
    spec:
      containers:
        - name: auth-management-service
          image: craigmiller160.ddns.net:30004/auth-management-service:1.5.10
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: auth-management-service-configmap
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: POSTGRES_ROOT_PASSWORD
            - name: oauth2.client-secret
              valueFrom:
                secretKeyRef:
                  name: auth-management-service-client-secret
                  key: client-secret
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: auth-management-service-service
spec:
  type: ClusterIP
  selector:
    app: auth-management-service
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
