apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-management-service
  template:
    metadata:
      labels:
        app: auth-management-service
    spec:
      containers:
        - name: auth-management-service
          image: localhost:32000/auth-management-service:1.0.0-SNAPSHOT
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: auth-management-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443/
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: auth-management-service-service
spec:
  type: NodePort
  selector:
    app: auth-management-service
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 31003
      protocol: TCP
